# Generated by Django 4.2.3 on 2023-07-13 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asegurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cuit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('país', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_poliza', models.CharField(max_length=50)),
                ('seccion', models.CharField(max_length=100)),
                ('asegurado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CORE.asegurado')),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CORE.aseguradora')),
            ],
        ),
    ]
