# Generated by Django 4.2.3 on 2023-07-13 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='asegurado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CORE.asegurado'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='aseguradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CORE.aseguradora'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='numero_poliza',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='seccion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
