# Generated by Django 4.2.3 on 2023-07-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0002_alter_poliza_asegurado_alter_poliza_aseguradora_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aseguradora',
            old_name='país',
            new_name='pais',
        ),
    ]
